name: Test Upload Artifact

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test file
        run: echo "Hello, GitHub Actions!" > test.txt

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.txt

      - name: Download test artifact
        uses: actions/download-artifact@v4
        with:
          name: test-artifact
          path: test-download
